pipeline {
  agent {
    docker { image 'nodejs:latest' }
  }
  stages {
    stage('Install') {
      steps {
          sh 'git checkout master'
          sh 'npm --version'
          sh 'ls && cd app && pwd && ls'
          sh 'npm uninstall *'
          sh 'npm install'
        }
    }

    // stage('Test') {
    //   parallel {
    //     stage('Static code analysis') {
    //         steps { sh 'npm run-script lint' }
    //     }
    //     stage('Unit tests') {
    //         steps { sh 'npm run-script test' }
    //     }
    //   }
    // }

    stage('Build') {
      steps {
          sh 'npm install @angular/cli@latest'
          sh 'cd app && pwd && ls && npm run-script build' 
        }
    }
  }
}