pipeline {
  agent { dockerfile true }
  stages {
    stage('Install & build') { 
      
      steps {
            // sh 'cd app && rm -rf package-lock.json && npm cache clean --force && npm install'
            sh 'cd app && rm -rf package-lock.json && sudo npm install'
            echo 'Start Building'
            sh 'cd app && npm run ng build'
            sh 'pwd && ls'
            // echo 'Start docker build'

            // sh 'cd app && docker build .'
        }
    }

    // stage('Test') {
    //   parallel {
    //     stage('Static code analysis') {
    //         steps { sh 'npm run-script lint' }
    //     }
    //     stage('Unit tests') {
    //         steps { sh 'npm run-script test' }
    //     }
    //   }
    // }

    stage('Docker image build') {
      steps {
        echo 'Start docker build'
        sh 'cd app && ls && pwd && docker build .'
      }
    }
    stage('Docker image push') {
      steps {
        echo 'Start docker image push'
        sh 'docker tag nginx mayurthakkar/grocery'
        sh 'docker push mayurthakkar/grocery:latest'
      }
    }
  }
}