pipeline {
  agent {
    docker { image 'node:12.18.1' }
  }
  environment {
        HOME = '.'
    }
  stages {
    stage('Clone') {
            steps {
                git branch: 'angular_11',
                    url: 'https://github.com/MayurThakkar/grocery-web.git'
            }
        }
    stage('Prepare Node and NPM') { // confirm nodejs plugin and setting
    steps {
          sh 'npm --version'
      } 
   }
    stage('Install') {
      steps {
            sh 'cd app && rm -rf package-lock.json && npm cache clean --force && npm install'
        }
    }

    // stage('Test') {
    //   parallel {
    //     stage('Static code analysis') {
    //         steps { sh 'npm run-script lint' }
    //     }
    //     stage('Unit tests') {
    //         steps { sh 'npm run-script test' }
    //     }
    //   }
    // }

    stage('Build') {
      steps {
            echo 'Start Building'
            sh 'cd app && npm run ng build' 
        }
    }
  }
}